# Generated by Django 4.2.3 on 2023-07-13 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=200, null=True)),
                ('table_number', models.IntegerField(null=True, unique=True)),
                ('play_time', models.DurationField(blank=True, default=datetime.time(0, 0), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=200, null=True)),
                ('table_number', models.IntegerField(null=True, unique=True)),
                ('play_time', models.DurationField(blank=True, default=datetime.time(0, 0), null=True)),
            ],
        ),
    ]
