# Generated by Django 4.2.3 on 2023-07-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='start',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
