# Generated by Django 4.1.5 on 2023-07-14 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_table_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='finish',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
