# Generated by Django 4.2.3 on 2023-07-17 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_table_finish_alter_table_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='finish',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='play_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
