# Generated by Django 4.2.3 on 2023-07-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_table_finish_alter_table_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='player',
            field=models.CharField(blank=True, default='player name?', max_length=200, null=True),
        ),
    ]
