# Generated by Django 4.1.5 on 2023-07-17 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_table_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='finish',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='table',
            name='play_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='table',
            name='player',
            field=models.CharField(blank=True, default='EMPTY', max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
