# Generated by Django 4.1.5 on 2023-07-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_table_finish_alter_table_play_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='finish',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='play_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
