# Generated by Django 4.2.3 on 2023-07-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_table_finish_alter_table_play_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiting',
            name='start',
        ),
        migrations.RemoveField(
            model_name='waiting',
            name='table_number',
        ),
    ]
