# Generated by Django 4.2.3 on 2023-07-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_waiting_start_remove_waiting_table_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_number']},
        ),
    ]
