# Generated by Django 4.2.3 on 2023-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_table_options_waiting_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
