# Generated by Django 4.2.3 on 2023-07-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
