# Generated by Django 4.2.3 on 2023-07-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
